@startuml

object virtualServer {
    <#lightBlue,#black>|= directives |= type |= priority |= reason |= note |
    <#white>| host | uint32_t | mandatory | Required to bind the server to a specific IP address | |
    <#white>| port | uint16_t | mandatory | A server cannot function without a port to listen on | |
    <#white>| server_name | string | default: "" | must be verify in case conflict host:port | |
    <#white>| client_max_body_size | int | default: 1024kb | Limiting the client body size prevents abuse | |
    <#white>| error_page | map<string, string> | default: "code" -> "error reason" | Default error page if not provided | |
    <#white>| locations | map<string, Location> | mandatory (at least one) | A server needs at least one location to handle request | |
}

object Location {
    <#lightBlue,#black>|= directives |= type |= priority |= reason |= note |
    <#white>| resource | string |mandatory | Without it, the server cannot handle a request to a specific location | This defines the resource path (e.g., ""/"") |
    <#white>| allowed_methods | vector<string> | default: GET | it's the most commonly used HTTP method | POST, DELETE can be optional |
    <#white>| root | string |mandatory | Essential for serving files | This specifies the directory on the filesystem that corresponds to the resource |
    <#white>| index | string | default:"index.html" | the default file html that will be server when client access "/" | |
    <#white>| auto_index | bool | default: false | Security reason | directory listing |
    <#white>| redirect | string | default:"" | Default to a empty string (no redirect) | |
    <#white>| cgi | bool | default:false | Security reason | Enable it only for specific locations if configured |
}
virtualServer "1" *-- "many" Location
@enduml
