@startuml
!pragma layout smetana

json "<b>Sockets</b>" as sockets {
["fd4", "fd5"]
}

json "<b>Ports</b>" as ports {
["8081", "8082"]
}

json "Flagged fds (from epoll_wait)" as fds {
["fd6", "fd7", "fd8"]
}

json "Connection" as connections {
	"Host" : "localhost",
	"Port" : 8081,
	"ConnectionFd" : 6,
	"Request" : "request",
	"Response" : "response",
	"Buffer" : "buffer",
	"VirtualServer" : "&virtualServer"
}

map "std::map<name, virtualServer&>" as map2 {
	um server => 0x01
	outro server => 0x02
}

map "std::map<name, virtualServer&>" as map3 {
	outro server => 0x03
}

map "<b>Default VirtualServers</b>\nstd::map<port, virtualServer&>" as defaultVirtualServers {
	8081 => 0x02
	80802 => 0x3
}

map "<b>VirtualServer lookup table</b>\nstd::map<pair<host, port>, map<name, virtualServer&>>" as vsLookupTable {
	localhost, 8081 *-> map2
	localhost, 8082 *--> map3
}


sockets "1" --> "1" ports
ports "1" --> "many" connections
fds "1" --> "1" connections : _connectionsMap
connections --> vsLookupTable
connections --> defaultVirtualServers : in case lookup fails


@enduml
